version: '3.5'

services:
  backend-app:
    build:
      context: ./
      dockerfile: ./docker/development/php/Dockerfile
    volumes:
      - ./:/app
    environment:
      APP_ENV: dev
      APP_SECRET: 714ecf9dfb0ce903b46ffb8e941a4fcf
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}?serverVersion=5.7

  nginx:
    build:
      context: ./
      dockerfile: ./docker/development/nginx/Dockerfile
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    volumes:
      - ./:/app

  db:
    build:
      context: ./
      dockerfile: ./docker/development/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: